require 'ffi-compiler/compile_task'

def self.java_home
  ENV["JAVA_HOME"] || "/usr/libexec/java_home"
end

FFI::Compiler::CompileTask.new('saxon') do |t|
  t.have_header?('jni.h', java_home)
  t.add_include_path(File.join(java_home, "include"))
  t.add_include_path(File.join(java_home, "include", "darwin"))
end
